# Generated by Django 4.0.6 on 2022-07-28 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dzongkhags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='boundary/%Y/%m/%d')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
