# Generated by Django 4.0.6 on 2022-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dcr',
            field=models.FileField(blank=True, upload_to='static/data/plan/dcr'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.FileField(blank=True, upload_to='static/data/plan/cover'),
        ),
    ]
