# Generated by Django 4.0.6 on 2022-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='approved_by',
            field=models.CharField(blank=True, choices=[('PPCM', 'PPCM'), ('NCHS', 'NCHS'), ('NCCHS', 'NCCHS'), ('LG', 'LG'), ('UNKNOWN', 'UNKNOWN')], max_length=100),
        ),
    ]
