# Generated by Django 4.0.6 on 2022-08-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': '3. Plan Data'},
        ),
        migrations.AlterModelOptions(
            name='dzongkhag',
            options={'verbose_name_plural': '1. Dzongkhag Boundary'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': '2. Plan Details'},
        ),
    ]
