# Generated by Django 4.0.6 on 2022-08-04 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plan_dcr_alter_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='excel',
            field=models.FileField(blank=True, upload_to='static/data/plan/excel'),
        ),
        migrations.AddField(
            model_name='plan',
            name='approved_by',
            field=models.CharField(blank=True, choices=[('PPCM', 'PPCM'), ('NCHS', 'NCHS'), ('NCCHS', 'NCCHS')], max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='approved_year',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='plan',
            name='report',
            field=models.FileField(blank=True, upload_to='static/data/plan/report'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(blank=True, choices=[('National Plan', 'National Plan'), ('Regional Development Plan', 'Regional Development Plan'), ('Local Spatails Plan', 'Local Spatails Plan'), ('Action Area Plan', 'Action Area Plan')], max_length=800),
        ),
    ]
