# Generated by Django 4.0.6 on 2022-07-29 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plans_alter_dzongkhags_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='dzongkhag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='boundary/%Y/%m/%d')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dzongkhag', models.CharField(choices=[('Bumthang', 'Bumthang'), ('Chhukha[', 'Chhukha'), ('Dagana', 'Dagana'), ('Gasa', 'Gasa'), ('Haa', 'Haa'), ('Lhuentse', 'Lhuentse'), ('Mongar', 'Mongar'), ('Paro', 'Paro'), ('Pema Gatshel', 'Pema Gatshel'), ('Punakha', 'Punakha'), ('Samdrup Jongkhar', 'Samdrup Jongkhar'), ('Samtse', 'Samtse'), ('Sarpang', 'Sarpang'), ('Thimphu', 'Thimphu'), ('Trashigang', 'Trashigang'), ('Trashi Yangtse', 'Trashi Yangtse'), ('Trongsa', 'Trongsa'), ('Tsirang', 'Tsirang'), ('Wangdue Phodrang', 'Wangdue Phodrang'), ('Zhemgang', 'Zhemgang')], max_length=250)),
                ('file', models.FileField(upload_to='planboundary/%Y/%m/%d')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='dzongkhags',
        ),
        migrations.DeleteModel(
            name='plans',
        ),
    ]
