# Generated by Django 4.0.6 on 2022-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_options_alter_dzongkhag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': '3. Plans Data'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': '2. Plans Detail'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='approved_by',
            field=models.CharField(blank=True, choices=[('PPCM', 'PPCM'), ('NCHS', 'NCHS'), ('NCCHS', 'NCCHS'), ('UNKNOWN', 'UNKNOWN'), ('LG', 'LG')], max_length=100),
        ),
    ]
