# Generated by Django 4.0.6 on 2022-08-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dzongkhag_plan_delete_dzongkhags_delete_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dzongkhag',
            name='file',
            field=models.FileField(upload_to='static/data/boundary/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dzongkhag',
            field=models.BigIntegerField(choices=[('1', 'Bumthang'), ('2', 'Chhukha'), ('3', 'Dagana'), ('4', 'Gasa'), ('5', 'Haa'), ('6', 'Lhuentse'), ('7', 'Mongar'), ('8', 'Paro'), ('9', 'Pema Gatshel'), ('10', 'Punakha'), ('11', 'Samdrup Jongkhar'), ('12', 'Samtse'), ('13', 'Sarpang'), ('14', 'Thimphu'), ('15', 'Trashigang'), ('16', 'Trashi Yangtse'), ('17', 'Trongsa'), ('18', 'Tsirang'), ('19', 'Wangdue Phodrang'), ('20', 'Zhemgang')], max_length=250),
        ),
        migrations.AlterField(
            model_name='plan',
            name='file',
            field=models.FileField(upload_to='static/data/planboundary/%Y/%m/%d'),
        ),
    ]
