# Generated by Django 4.0.6 on 2022-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_data_excel_plan_approved_by_plan_approved_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='approved_year',
            new_name='approved_date',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_year',
            new_name='plan_date',
        ),
    ]
