# Generated by Django 4.0.6 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_approved_year_plan_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(blank=True, choices=[('National Plan', 'National Plan'), ('Regional Development Plan', 'Regional Development Plan'), ('Local Spatail Plan', 'Local Spatail Plan'), ('Action Area Plan', 'Action Area Plan')], max_length=800),
        ),
    ]
