# Generated by Django 4.0.6 on 2022-08-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_data_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='database',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
