# Generated by Django 4.0.6 on 2022-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_plan_dzongkhag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='file',
        ),
        migrations.AddField(
            model_name='plan',
            name='boundray',
            field=models.FileField(blank=True, upload_to='static/data/plan/boundary/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plot',
            field=models.FileField(blank=True, upload_to='static/data/plan/plot/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='plan',
            name='precient',
            field=models.FileField(blank=True, upload_to='static/data/plan/precient/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dzongkhag',
            field=models.BigIntegerField(choices=[(1, 'Bumthang'), (2, 'Chhukha'), (3, 'Dagana'), (4, 'Gasa'), (5, 'Haa'), (6, 'Lhuentse'), (7, 'Mongar'), (8, 'Paro'), (9, 'Pema Gatshel'), (10, 'Punakha'), (11, 'Samdrup Jongkhar'), (12, 'Samtse'), (13, 'Sarpang'), (14, 'Thimphu'), (15, 'Trashigang'), (16, 'Trashi Yangtse'), (17, 'Tsirang'), (18, 'Trongsa'), (19, 'Wangdue Phodrang'), (20, 'Zhemgang')]),
        ),
    ]
