# Generated by Django 4.0.6 on 2022-08-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_data_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='plot',
        ),
    ]
