# Generated by Django 4.0.6 on 2022-08-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_plan_file_plan_boundray_plan_plot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='boundray',
            new_name='boundary',
        ),
    ]
